[package]
  name = "hyprbar"
  version = "0.1.0"
  edition = "2024"

[dependencies]
  smithay-client-toolkit = "0.20"
  wayland-client = "0.31"
  wayland-backend = { version = "0.3", features = ["client_system"] }
  raw-window-handle = "0.6"

  calloop = "0.14"
  calloop-wayland-source = "0.4"

  vello = "0.8"
  pollster = "0.4"
  parley = "0.9"

  chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }

  ureq = { version = "3.3.0", default-features = false, features = ["rustls"] }
  serde = { version = "1", features = ["derive"] }
  serde_json = "1"

  image = { version = "0.25", default-features = false, features = ["jpeg", "png"] }

  anyhow = "1"
  thiserror = "2"

  log = "0.4"
  env_logger = "0.11"

[profile.dev]
  opt-level = 1

[profile.release]
  lto = "thin"
  codegen-units = 1
