// ─── < Structs > ────────────────────────────────────────────────────

#[derive(Debug, Clone, Copy)]
pub struct Tokens {
    pub bar_height: f32,
    pub bar_margin_top: f32,
    pub bar_margin_x: f32,

    pub pill_height: f32,
    pub pill_gap: f32,
    pub pill_padding_x: f32,
    pub pill_padding_y: f32,
    pub pill_radius: f32,

    pub dropdown_width: f32,
    pub dropdown_height: f32,
    pub dropdown_margin_top: f32,
    pub dropdown_margin_bottom: f32,
    pub dropdown_padding_x: f32,
    pub dropdown_padding_y: f32,
    pub dropdown_item_height: f32,
    pub dropdown_item_gap: f32,
    pub dropdown_radius: f32,

    pub system_panel_width: f32,
    pub system_panel_padding_x: f32,
    pub system_panel_padding_y: f32,
    pub system_section_gap: f32,
    pub system_metric_row_height: f32,
    pub system_metric_gap: f32,
    pub system_meter_height: f32,
    pub system_meter_gap: f32,
    pub system_updates_row_height: f32,
    pub system_button_height: f32,
    pub system_button_gap: f32,
    pub system_button_radius: f32,
    pub system_temp_gauge_max_c: f32,
    pub system_icon_gap: f32,

    pub date_panel_padding_x: f32,
    pub date_panel_padding_y: f32,
    pub date_header_gap: f32,
    pub date_weekday_row_height: f32,
    pub date_cell_size: f32,
    pub date_cell_gap: f32,
    pub date_nav_button_size: f32,
    pub date_nav_button_gap: f32,
    pub date_nav_button_radius: f32,

    pub clock_panel_width: f32,
    pub clock_panel_padding_x: f32,
    pub clock_panel_padding_y: f32,
    pub clock_header_height: f32,
    pub clock_header_time_scale: f32,
    pub clock_section_gap: f32,
    pub clock_row_height: f32,
    pub clock_row_gap: f32,
    pub clock_row_inner_gap: f32,
    pub clock_tag_padding_x: f32,
    pub clock_tag_padding_y: f32,
    pub clock_tag_radius: f32,

    pub weather_panel_width: f32,
    pub weather_panel_padding_x: f32,
    pub weather_panel_padding_y: f32,
    pub weather_header_height: f32,
    pub weather_temp_scale: f32,
    pub weather_header_icon_scale: f32,
    pub weather_section_gap: f32,
    pub weather_details_row_height: f32,
    pub weather_forecast_day_height: f32,
    pub weather_forecast_icon_height: f32,
    pub weather_forecast_max_height: f32,
    pub weather_forecast_min_height: f32,

    pub command_panel_width: f32,
    pub command_panel_padding_x: f32,
    pub command_panel_padding_y: f32,
    pub command_slider_row_height: f32,
    pub command_slider_gap: f32,
    pub command_icon_slot: f32,
    pub command_track_height: f32,
    pub command_handle_radius: f32,
    pub command_value_width: f32,
    pub command_inner_gap: f32,
    pub command_section_gap: f32,
    pub command_media_height: f32,
    pub command_media_button_size: f32,
    pub command_media_play_size: f32,
    pub command_media_button_gap: f32,
    pub command_media_button_radius: f32,
    pub command_toggle_height: f32,
    pub command_toggle_radius: f32,
    pub command_toggle_gap: f32,

    pub icon_scale: f32,

    pub weather_inner_gap: f32,

    pub workspace_slot_gap: f32,
    pub workspace_active_width_scale: f32,
    pub workspace_active_radius_scale: f32,
    pub workspace_inactive_width_scale: f32,
    pub workspace_inactive_height_scale: f32,
    pub workspace_inactive_radius_scale: f32,

    pub avatar_border_width: f32,
    pub avatar_outer_radius_offset: f32,

    pub notification_dot_radius: f32,
    pub notification_dot_x_overlap_scale: f32,
    pub notification_dot_y_icon_scale: f32,

    pub shadow_offset_y: f32,
}

// ─── < Implementations > ────────────────────────────────────────────────────

impl Default for Tokens {
    fn default() -> Self {
        Self {
            bar_height: 40.0,
            bar_margin_top: 5.0,
            bar_margin_x: 12.0,

            pill_height: 29.0,
            pill_gap: 7.0,
            pill_padding_x: 11.0,
            pill_padding_y: 6.0,
            pill_radius: 13.0,

            dropdown_width: 220.0,
            dropdown_height: 150.0,
            dropdown_margin_top: 8.0,
            dropdown_margin_bottom: 8.0,
            dropdown_padding_x: 12.0,
            dropdown_padding_y: 10.0,
            dropdown_item_height: 34.0,
            dropdown_item_gap: 4.0,
            dropdown_radius: 14.0,

            system_panel_width: 232.0,
            system_panel_padding_x: 14.0,
            system_panel_padding_y: 12.0,
            system_section_gap: 10.0,
            system_metric_row_height: 30.0,
            system_metric_gap: 8.0,
            system_meter_height: 5.0,
            system_meter_gap: 4.0,
            system_updates_row_height: 22.0,
            system_button_height: 30.0,
            system_button_gap: 6.0,
            system_button_radius: 9.0,
            system_temp_gauge_max_c: 90.0,
            system_icon_gap: 6.0,

            date_panel_padding_x: 14.0,
            date_panel_padding_y: 12.0,
            date_header_gap: 10.0,
            date_weekday_row_height: 16.0,
            date_cell_size: 26.0,
            date_cell_gap: 2.0,
            date_nav_button_size: 20.0,
            date_nav_button_gap: 6.0,
            date_nav_button_radius: 6.0,

            clock_panel_width: 232.0,
            clock_panel_padding_x: 14.0,
            clock_panel_padding_y: 12.0,
            clock_header_height: 38.0,
            clock_header_time_scale: 1.8,
            clock_section_gap: 10.0,
            clock_row_height: 18.0,
            clock_row_gap: 9.0,
            clock_row_inner_gap: 8.0,
            clock_tag_padding_x: 5.0,
            clock_tag_padding_y: 1.5,
            clock_tag_radius: 5.0,

            weather_panel_width: 248.0,
            weather_panel_padding_x: 14.0,
            weather_panel_padding_y: 12.0,
            weather_header_height: 38.0,
            weather_temp_scale: 1.8,
            weather_header_icon_scale: 2.0,
            weather_section_gap: 11.0,
            weather_details_row_height: 16.0,
            weather_forecast_day_height: 14.0,
            weather_forecast_icon_height: 24.0,
            weather_forecast_max_height: 15.0,
            weather_forecast_min_height: 14.0,

            command_panel_width: 264.0,
            command_panel_padding_x: 14.0,
            command_panel_padding_y: 13.0,
            command_slider_row_height: 22.0,
            command_slider_gap: 11.0,
            command_icon_slot: 20.0,
            command_track_height: 6.0,
            command_handle_radius: 7.0,
            command_value_width: 34.0,
            command_inner_gap: 10.0,
            command_section_gap: 12.0,
            command_media_height: 34.0,
            command_media_button_size: 26.0,
            command_media_play_size: 30.0,
            command_media_button_gap: 4.0,
            command_media_button_radius: 8.0,
            command_toggle_height: 32.0,
            command_toggle_radius: 9.0,
            command_toggle_gap: 6.0,

            icon_scale: 1.2,

            weather_inner_gap: 5.0,

            workspace_slot_gap: 7.0,
            workspace_active_width_scale: 1.7,
            workspace_active_radius_scale: 0.5,
            workspace_inactive_width_scale: 1.1,
            workspace_inactive_height_scale: 1.0,
            workspace_inactive_radius_scale: 0.35,

            avatar_border_width: 2.5,
            avatar_outer_radius_offset: 0.5,

            notification_dot_radius: 3.5,
            notification_dot_x_overlap_scale: 0.5,
            notification_dot_y_icon_scale: 0.35,

            shadow_offset_y: 1.0,
        }
    }
}
