// ─── < Structs > ────────────────────────────────────────────────────

#[derive(Debug, Clone, Copy)]
pub struct Tokens {
    pub bar_height: f32,
    pub bar_margin_top: f32,
    pub bar_margin_x: f32,

    pub pill_height: f32,
    pub pill_gap: f32,
    pub pill_padding_x: f32,
    pub pill_padding_y: f32,
    pub pill_radius: f32,

    pub dropdown_width: f32,
    pub dropdown_height: f32,
    pub dropdown_margin_top: f32,
    pub dropdown_margin_bottom: f32,
    pub dropdown_padding_x: f32,
    pub dropdown_padding_y: f32,
    pub dropdown_item_height: f32,
    pub dropdown_item_gap: f32,
    pub dropdown_radius: f32,
    pub dropdown_border_width: f32,

    pub dropdown_panel_width: f32,
    pub dropdown_panel_padding_x: f32,
    pub dropdown_panel_padding_y: f32,
    pub dropdown_header_height: f32,
    pub dropdown_section_gap: f32,
    pub dropdown_title_scale: f32,
    pub dropdown_subtitle_scale: f32,
    pub dropdown_body_scale: f32,

    pub system_metric_row_height: f32,
    pub system_metric_gap: f32,
    pub system_meter_height: f32,
    pub system_meter_gap: f32,
    pub system_updates_row_height: f32,
    pub system_button_height: f32,
    pub system_button_gap: f32,
    pub system_button_radius: f32,
    pub system_temp_gauge_max_c: f32,
    pub system_icon_slot: f32,

    pub system_load_warn_fraction: f32,
    pub system_load_crit_fraction: f32,
    pub system_temp_warn_c: f32,
    pub system_temp_crit_c: f32,

    pub date_weekday_row_height: f32,
    pub date_cell_size: f32,
    pub date_cell_gap: f32,
    pub date_nav_button_size: f32,
    pub date_nav_button_gap: f32,
    pub date_nav_button_radius: f32,
    pub date_today_marker_scale: f32,
    pub date_week_radius: f32,
    pub date_week_highlight_alpha: f32,

    pub clock_header_time_scale: f32,
    pub clock_row_height: f32,
    pub clock_row_gap: f32,
    pub clock_row_inner_gap: f32,
    pub clock_chip_padding_x: f32,
    pub clock_chip_padding_y: f32,
    pub clock_chip_radius: f32,
    pub clock_icon_slot: f32,

    pub weather_temp_scale: f32,
    pub weather_header_icon_scale: f32,
    pub weather_details_row_height: f32,
    pub weather_forecast_day_height: f32,
    pub weather_forecast_icon_height: f32,
    pub weather_forecast_max_height: f32,
    pub weather_forecast_min_height: f32,
    pub weather_today_pill_radius: f32,
    pub weather_today_pill_padding_x: f32,
    pub weather_today_pill_inset_y: f32,

    pub command_panel_width: f32,
    pub command_panel_padding_x: f32,
    pub command_panel_padding_y: f32,
    pub command_slider_row_height: f32,
    pub command_thick_track_height: f32,
    pub command_card_radius: f32,
    pub command_card_padding_x: f32,
    pub command_card_padding_y: f32,
    pub command_card_gap: f32,
    pub command_card_title_height: f32,
    pub command_wifi_card_height: f32,
    pub command_sound_card_height: f32,
    pub command_icon_circle_radius: f32,
    pub command_circle_button_radius: f32,
    pub command_circle_button_gap: f32,

    pub profile_panel_width: f32,
    pub profile_panel_padding_x: f32,
    pub profile_panel_padding_y: f32,
    pub profile_avatar_size: f32,
    pub profile_avatar_gap: f32,
    pub profile_avatar_border_width: f32,
    pub profile_section_gap: f32,
    pub profile_button_height: f32,
    pub profile_button_gap: f32,
    pub profile_button_radius: f32,
    pub profile_button_inner_gap: f32,

    pub icon_scale: f32,

    pub weather_inner_gap: f32,

    pub workspace_slot_gap: f32,
    pub workspace_active_width_scale: f32,
    pub workspace_active_radius_scale: f32,
    pub workspace_inactive_width_scale: f32,
    pub workspace_inactive_height_scale: f32,
    pub workspace_inactive_radius_scale: f32,

    pub avatar_border_width: f32,
    pub avatar_outer_radius_offset: f32,

    pub notification_dot_radius: f32,
    pub notification_dot_x_overlap_scale: f32,
    pub notification_dot_y_icon_scale: f32,

    pub notification_panel_width: f32,
    pub notification_header_height: f32,
    pub notification_row_height: f32,
    pub notification_empty_height: f32,
    pub notification_clear_width: f32,
    pub notification_clear_height: f32,
    pub notification_row_dot_radius: f32,
    pub notification_row_text_inset: f32,
}

// ─── < Implementations > ────────────────────────────────────────────────────

impl Default for Tokens {
    fn default() -> Self {
        Self {
            bar_height: 40.0,
            bar_margin_top: 5.0,
            bar_margin_x: 12.0,

            pill_height: 29.0,
            pill_gap: 7.0,
            pill_padding_x: 11.0,
            pill_padding_y: 6.0,
            pill_radius: 13.0,

            dropdown_width: 220.0,
            dropdown_height: 150.0,
            dropdown_margin_top: 8.0,
            dropdown_margin_bottom: 8.0,
            dropdown_padding_x: 12.0,
            dropdown_padding_y: 10.0,
            dropdown_item_height: 34.0,
            dropdown_item_gap: 4.0,
            dropdown_radius: 16.0,
            dropdown_border_width: 1.0,

            dropdown_panel_width: 222.0,
            dropdown_panel_padding_x: 14.0,
            dropdown_panel_padding_y: 12.0,
            dropdown_header_height: 38.0,
            dropdown_section_gap: 12.0,
            dropdown_title_scale: 1.15,
            dropdown_subtitle_scale: 0.78,
            dropdown_body_scale: 0.9,

            system_metric_row_height: 30.0,
            system_metric_gap: 8.0,
            system_meter_height: 6.0,
            system_meter_gap: 4.0,
            system_updates_row_height: 22.0,
            system_button_height: 30.0,
            system_button_gap: 6.0,
            system_button_radius: 9.0,
            system_temp_gauge_max_c: 90.0,
            system_icon_slot: 22.0,

            system_load_warn_fraction: 0.75,
            system_load_crit_fraction: 0.90,
            system_temp_warn_c: 70.0,
            system_temp_crit_c: 85.0,

            date_weekday_row_height: 16.0,
            date_cell_size: 26.0,
            date_cell_gap: 2.0,
            date_nav_button_size: 22.0,
            date_nav_button_gap: 6.0,
            date_nav_button_radius: 6.0,
            date_today_marker_scale: 0.82,
            date_week_radius: 8.0,
            date_week_highlight_alpha: 0.12,

            clock_header_time_scale: 1.8,
            clock_row_height: 18.0,
            clock_row_gap: 10.0,
            clock_row_inner_gap: 8.0,
            clock_chip_padding_x: 5.0,
            clock_chip_padding_y: 1.5,
            clock_chip_radius: 5.0,
            clock_icon_slot: 20.0,

            weather_temp_scale: 1.8,
            weather_header_icon_scale: 2.0,
            weather_details_row_height: 16.0,
            weather_forecast_day_height: 14.0,
            weather_forecast_icon_height: 24.0,
            weather_forecast_max_height: 15.0,
            weather_forecast_min_height: 14.0,
            weather_today_pill_radius: 9.0,
            weather_today_pill_padding_x: 3.0,
            weather_today_pill_inset_y: 2.0,

            command_panel_width: 264.0,
            command_panel_padding_x: 14.0,
            command_panel_padding_y: 13.0,
            command_slider_row_height: 20.0,
            command_thick_track_height: 10.0,
            command_card_radius: 14.0,
            command_card_padding_x: 10.0,
            command_card_padding_y: 8.0,
            command_card_gap: 8.0,
            command_card_title_height: 16.0,
            command_wifi_card_height: 50.0,
            command_sound_card_height: 52.0,
            command_icon_circle_radius: 14.0,
            command_circle_button_radius: 22.0,
            command_circle_button_gap: 12.0,

            profile_panel_width: 248.0,
            profile_panel_padding_x: 16.0,
            profile_panel_padding_y: 16.0,
            profile_avatar_size: 52.0,
            profile_avatar_gap: 12.0,
            profile_avatar_border_width: 1.5,
            profile_section_gap: 14.0,
            profile_button_height: 34.0,
            profile_button_gap: 8.0,
            profile_button_radius: 9.0,
            profile_button_inner_gap: 7.0,

            icon_scale: 1.2,

            weather_inner_gap: 5.0,

            workspace_slot_gap: 7.0,
            workspace_active_width_scale: 1.7,
            workspace_active_radius_scale: 0.5,
            workspace_inactive_width_scale: 1.1,
            workspace_inactive_height_scale: 1.0,
            workspace_inactive_radius_scale: 0.35,

            avatar_border_width: 1.5,
            avatar_outer_radius_offset: 2.5,

            notification_dot_radius: 3.5,
            notification_dot_x_overlap_scale: 0.5,
            notification_dot_y_icon_scale: 0.35,

            notification_panel_width: 340.0,
            notification_header_height: 38.0,
            notification_row_height: 46.0,
            notification_empty_height: 42.0,
            notification_clear_width: 66.0,
            notification_clear_height: 22.0,
            notification_row_dot_radius: 3.0,
            notification_row_text_inset: 12.0,
        }
    }
}
